### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by Dexxa1024** [CloudVisionApps/PhyrePanel#1]
I;ve tried to install this but when i go to my main i[ address all i get is a white screen and yellow text saying phyre hosting panel  not no access to the panel nor any login details

is there a port number to be used with the panel?

**Comment by bobicloudvision** [comment]
Hello, the admin panel can be opened on port 8443.
for example: http://0.0.0.127:8443

**Comment by bobicloudvision** [comment]
Join to our discord group: https://discord.gg/yfFWfrfwTZ
