### ISSUE TITLE
error on edit & create hosting plan

### ISSUE THREAD

**Issue by mrjk990** [CloudVisionApps/PhyrePanel#3]
BladeUI  \ Icons \ Exceptions\ SvgNotFound

PHP 8.2.0
10.48.7
Svg by name "fluentui-database-plug-connected-20" from set "default" not found.

also when try create website i do not see any hosting plans 

also when try install the panel on server i get error 
`/usr/local/phyre/php/bin/php: error while loading shared libraries: libsodium.so.23: cannot open shared object file: No such file or directory` 

and fixing by "apt-get install libsodium-dev -y"

i use ubuntu 22.04

**Comment by bobicloudvision** [comment]
Hello, the issues with SVG is fixed. We will add update functionality in admin panel to get the latest version of panel.
Hosting plans you can add manually from panel.
I will check libsodium also...
Join to telegram group if you have any questions.
